dist: focal
language: python
python:
  - "3.12"

service_name: travis-pro

cache: pip


install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

script:
  # Added --exclude to ignore the virtual environment
  - black --check . --exclude 'myenv/' || true  # This will not break the build
  
  # Added --exclude for flake8 as well
  - flake8 . --exclude=myenv/
  
  - coverage run --source='.' manage.py test

after_success:
  - COVERALLS_REPO_NAME=sumit8692/swe1-app coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-2"
  app: "djangotutorial"     
  env: "django-clean-v3"
  bucket_name: "elasticbeanstalk-us-west-2-563336977573"
  on:
    branch: main