dist: focal
language: python
python:
  - "3.12"

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

script:
  # Added --exclude to ignore the virtual environment
  - black --check . --exclude 'myenv/' || true  # This will not break the build
  
  # Added --exclude for flake8 as well
  - flake8 . --exclude=myenv/
  
  - coverage run --source='.' manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-2"
  app: "swe1-app"
  env: "django-clean-v3"
  # Space removed and double-check if this should be us-east-1 to match region above
  bucket_name: "elasticbeanstalk-us-west-2-563336977573"
  on:
    branch: main