dist: focal
language: python
python:
  - "3.12"

# Speed up subsequent builds
cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

script:
  # 1. Formatting check (Strictly 88 chars)
  - black --check .
  
  # 2. Linting check (Will ignore errors if you've set up .flake8)
  - flake8 .
  
  # 3. Running tests for 'mysite' and 'polls'
  - coverage run --source='.' manage.py test

after_success:
  # Sends results to coveralls.io
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "swe1-app"
  env: "django-clean-v3" # Ensure this matches your AWS console exactly
  bucket_name: "elasticbeanstalk-us-west-2-563336977573 " # Find this in your AWS S3 console
  on:
    branch: main
